-- FIREBOMBA - DATABASE
-- PostgreSQL / Supabase
-- =========================================================


-- =========================================================
-- 1. BILIK
-- =========================================================

CREATE TABLE IF NOT EXISTS bilik (
    bilik_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bilik_number VARCHAR(50) NOT NULL,
    household_name VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


-- =========================================================
-- 2. ROOMS
-- =========================================================

CREATE TABLE IF NOT EXISTS rooms (
    room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    last_updated TIMESTAMPTZ,
    camera_enabled BOOLEAN DEFAULT FALSE,

    space_type VARCHAR(20) NOT NULL DEFAULT 'BILIK_ROOM',

    bilik_id INTEGER,

    CONSTRAINT rooms_space_type_check
        CHECK (space_type IN ('BILIK_ROOM', 'DAPUR', 'SADAU')),

    CONSTRAINT rooms_bilik_fk
        FOREIGN KEY (bilik_id)
        REFERENCES bilik(bilik_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 3. USERS
-- =========================================================

CREATE TABLE users (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    bilik_id INTEGER NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT users_bilik_fk
        FOREIGN KEY (bilik_id)
        REFERENCES Bilik(bilik_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 4. SENSOR READINGS
-- =========================================================

CREATE TABLE IF NOT EXISTS sensor_readings (
    reading_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    flame_detected BOOLEAN,
    temperature REAL,
    humidity REAL,
    smoke REAL,
    co REAL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT sensor_readings_room_fk
        FOREIGN KEY (room_id)
        REFERENCES rooms(room_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 5. ACTUATORS
-- =========================================================

CREATE TABLE IF NOT EXISTS actuators (
    actuator_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id INTEGER NOT NULL,
    last_updated TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    waterpump_enabled BOOLEAN DEFAULT FALSE,
    CONSTRAINT actuators_room_fk
        FOREIGN KEY (room_id)
        REFERENCES rooms(room_id)
        ON DELETE CASCADE
);


-- =========================================================
-- 6. SENSOR AGGREGATES
-- =========================================================

CREATE TABLE IF NOT EXISTS sensor_aggregates (
    aggregate_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    room_id INTEGER NOT NULL,

    window_start TIMESTAMPTZ,
    window_end TIMESTAMPTZ,

    avg_temperature REAL,
    max_temperature REAL,

    avg_humidity REAL,

    avg_smoke REAL,
    max_smoke REAL,

    avg_co REAL,
    max_co REAL,

    flame_trigger_count INTEGER,
    total_readings INTEGER,

    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT sensor_aggregates_room_fk
        FOREIGN KEY (room_id)
        REFERENCES rooms(room_id)
        ON DELETE CASCADE
);

-- Mock biliks
INSERT INTO bilik (bilik_number, household_name)
VALUES
    ('BILIK-01', 'Household Ali'),
    ('BILIK-02', 'Household Abu'),
    ('BILIK-03', 'Household Ahmad');



INSERT INTO rooms
    (name, status, last_updated, camera_enabled, space_type, bilik_id)
VALUES
    -- Bilik 1
    ('Ali Bedroom', 'NORMAL', '2026-09-16 20:00:00+08', TRUE, 'BILIK_ROOM', 1),
    ('Ali Kitchen', 'NORMAL', '2026-09-16 20:00:00+08', TRUE, 'DAPUR', 1),

    -- Bilik 2
    ('Abu Bedroom', 'NORMAL', '2026-09-16 20:01:00+08', TRUE, 'BILIK_ROOM', 2),
    ('Abu Kitchen', 'NORMAL', '2026-09-16 20:01:00+08', FALSE, 'DAPUR', 2),

    -- Bilik 3
    ('Ahmad Bedroom', 'NORMAL', '2026-09-16 20:02:00+08', TRUE, 'BILIK_ROOM', 3),
    ('Ahmad Kitchen', 'NORMAL', '2026-09-16 20:02:00+08', FALSE, 'DAPUR', 3);

